default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: sommer
  password: pwd123!

development:
  <<: *default
  database: purchase_sample_development

test:
  <<: *default
  database: purchase_sample_test
